#!/work/_builds/darwin-x64/formal/python3-native/yosyshq/bin/python3.11
# -*- coding: utf-8 -*-
import re
import sys
from scy.scy import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
